---
name: POE-Filter-SimpleHTTP
version: 0.01
author:
  - 'Nicholas Perez <nperez@cpan.org>'
abstract: A simple client/server HTTP filter for POE
license: gpl
resources:
  license: http://opensource.org/licenses/gpl-license.php
  repository: http://github.com/nperez/pfsh/tree/master
build_requires:
  Compress::Zlib: 2.012
  LWP: 5.822
  Moose: 0.75
  Regexp::Common: 2.122
  Test::More: 0
  UNIVERSAL::isa: 1.01
  URI: 1.37
provides:
  POE::Filter::SimpleHTTP:
    file: lib/POE/Filter/SimpleHTTP.pm
    version: 0.01
  POE::Filter::SimpleHTTP::Error:
    file: lib/POE/Filter/SimpleHTTP/Error.pm
    version: 0.01
  POE::Filter::SimpleHTTP::Regex:
    file: lib/POE/Filter/SimpleHTTP/Regex.pm
    version: 0.01
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
